### ISSUE TITLE
DynamoDBテーブル定義作成

### ISSUE THREAD

**Issue by yosnak13** [yosnak13/youtube-line-notification-app#8]
* #6 

## Todo

DynamoDBのテーブル定義。現状2テーブルで十分。
- お気に入りチャンネルテーブル（UserFavoriteChannel）
- 最新動画テーブル（NewestMovie）

**Comment by yosnak13** [comment]
## NewestMovies

| MovieId（PK） | ChannelId | Title | ThumbnailUrl | MovieUrl | CreateDateTime
| -- | -- | -- | -- | -- | --


## UserFavoriteChannels

UserId（PK） | ChannelId（SK） | ChannelName | CreateDateTime
-- | -- | -- | --

**Comment by yosnak13** [comment]
## sam template

メモとして残す

```yml
  UserFavoriteChannelsDynamoDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: UserFavoriteChannels
      PrimaryKey:
        Name: UserId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  NewestMoviesDynamoDB:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: NewestMovies
      PrimaryKey:
        Name: UserId
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
```
